#!/usr/bin/env node
// Complete project review flow with real HTTP/state/media and no external generation.
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require('playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const output=process.env.STUDIO_REVIEW_SCREENSHOTS||'/tmp/studio-review-browser';
await mkdir(output,{recursive:true});
const child=spawn('python3',['-u','cb-studio/project_review_fixture.py'],{cwd:root,stdio:['ignore','pipe','pipe']});
let browser,log='';
try {
  const address=await new Promise((resolve,reject)=>{
    const timer=setTimeout(()=>reject(new Error('Test server startup timeout: '+log)),30000);
    child.stdout.on('data',data=>{log+=data.toString();const line=log.split('\n').find(s=>s.startsWith('{"url"'));if(line){clearTimeout(timer);resolve(JSON.parse(line).url);}});
    child.stderr.on('data',data=>{log+=data.toString();});
    child.on('exit',code=>{clearTimeout(timer);reject(new Error('Test server exited '+code+': '+log));});
  });
  browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
  const context=await browser.newContext({viewport:{width:1440,height:1100}});
  const origin=new URL(address).origin;
  await context.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());
  const page=await context.newPage(),errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(address);
  await page.locator('#pc_first').getByRole('button',{name:'Open project',exact:true}).click();
  await page.locator('#sp-budget-amount').fill('20');
  await page.getByRole('button',{name:'Approve allowance & prepare',exact:true}).click();
  await page.locator('.sp-shot-card').first().waitFor();
  assert.equal(await page.locator('.sp-shot-card').count(),2);
  await page.screenshot({path:path.join(output,'01-episode-board.png'),fullPage:true});
  await page.locator('[data-open-shot="S1.SH1"]').click();
  await page.getByRole('button',{name:'Approve SEE & continue',exact:true}).click();
  await page.getByRole('button',{name:'Approve HEAR & continue',exact:true}).click();
  await page.locator('#sp-direction').fill('Make the reaction more hesitant. Keep the voice and geography.');
  await page.getByRole('button',{name:'Send direction',exact:true}).click();
  await page.getByRole('button',{name:'Apply & prepare',exact:true}).waitFor();
  assert.match(await page.locator('#sp-proposal').innerText(),/Preserves: HEAR/);
  await page.screenshot({path:path.join(output,'02-edit-preview.png'),fullPage:true});
  await page.getByRole('button',{name:'Apply & prepare',exact:true}).click();
  await page.getByRole('button',{name:'Approve SEE & continue',exact:true}).click();
  await page.getByRole('button',{name:'Approve request & render',exact:true}).click();
  await page.getByRole('button',{name:'Approve WATCH & continue',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#sp-scope')?.textContent.includes('S1.SH2'));
  await page.locator('[data-view="review"]').click();
  assert.match(await page.locator('#sp-tracks').innerText(),/Missing approved footage/);
  await page.locator('[data-view="shot"]').click();
  await page.getByRole('button',{name:'Approve SEE & continue',exact:true}).click();
  await page.getByRole('button',{name:'Approve HEAR & continue',exact:true}).click();
  await page.getByRole('button',{name:'Approve request & render',exact:true}).click();
  await page.getByRole('button',{name:'Approve WATCH & continue',exact:true}).click();
  await page.locator('[data-view="review"]').click();
  await page.locator('[data-clip="1"]').click();
  await page.locator('#sp-moment-note').fill('The reaction needs room to land.');
  await page.getByRole('button',{name:'Save timed note',exact:true}).click();
  await page.getByRole('button',{name:'Mark addressed',exact:true}).click();
  await page.getByRole('button',{name:'Mark incoming join reviewed',exact:true}).click();
  await page.getByRole('button',{name:'Approve episode assembly',exact:true}).click();
  await page.getByRole('button',{name:'Create finishing handoff',exact:true}).click();
  const download=page.getByRole('link',{name:'Download timeline',exact:true});await download.waitFor();
  const response=await context.request.get(await download.getAttribute('href'));
  assert.equal(response.status(),200);assert.match(await response.text(),/<fcpxml version="1.8">/);
  await page.locator('[data-clip="0"]').click();
  const player=page.locator('#sp-episode-player');await player.evaluate(video=>{window.reviewPlayer=video;});
  await page.waitForTimeout(4400);
  assert.equal(await player.evaluate(video=>video===window.reviewPlayer),true,'Polling must preserve the player');
  await page.getByRole('button',{name:'Play episode',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#sp-play-position')?.textContent.includes('S1.SH2'),null,{timeout:7000});
  await page.screenshot({path:path.join(output,'03-episode-review.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.locator('[data-view="board"]').click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'No horizontal overflow on mobile');
  await page.screenshot({path:path.join(output,'04-mobile-board.png'),fullPage:true});
  await page.locator('[data-open-shot="S1.SH2"]').click();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'No horizontal overflow in the shot workspace');
  assert.deepEqual(errors,[]);
  assert.equal(await page.locator('#sp-error').innerText(),'');
  await page.setViewportSize({width:1440,height:1100});
  await page.getByRole('button',{name:'Edit project library',exact:true}).click();
  await page.getByRole('button',{name:'Character states',exact:true}).click();
  const form=page.locator('#workspace-dialog form');
  await form.locator('[name="name"]').fill('Soaked');
  await form.locator('[name="notes"]').fill('Wet fur, same character identity.');
  await form.locator('[name="episode"]').selectOption('1');
  await form.locator('[name="scenes"]').fill('1');
  const reference=await context.request.get(origin+'/projects/first/assets/hero.png');
  await form.locator('[name="image"]').setInputFiles({name:'soaked.png',mimeType:'image/png',buffer:await reference.body()});
  await page.locator('#sp-state-image').waitFor({state:'visible'});
  await form.locator('[name="approve"]').check();
  await form.getByRole('button',{name:'Save character state',exact:true}).click();
  await page.locator('#modal.show').waitFor({state:'hidden'});
  await page.locator('[data-open-shot="S1.SH2"]').click();
  await page.locator('#sp-continuity summary').filter({hasText:'Character states'}).click();
  const stateSelect=page.locator('[data-character-state="Hero"]');
  const option=stateSelect.locator('option').filter({hasText:'Soaked'});assert.equal(await option.count(),1);
  await stateSelect.selectOption(await option.getAttribute('value'));
  await page.getByRole('button',{name:'Preview state change',exact:true}).click();
  await page.getByRole('button',{name:'Keep current version',exact:true}).click();
  await page.getByRole('button',{name:'All projects',exact:true}).click();
  await page.locator('#pc_second').getByRole('button',{name:'Open project',exact:true}).click();
  await page.getByRole('button',{name:'Edit project library',exact:true}).click();
  await page.getByRole('button',{name:'Character states',exact:true}).click();
  await page.locator('#workspace-dialog [name="existing"]').waitFor({state:'visible'});
  assert.equal(await page.locator('#workspace-dialog [name="existing"] option').count(),1,'Character states must remain project-local');
  assert.deepEqual(errors,[]);
  console.log('PASS: board, SEE/HEAR/request/WATCH, preview/apply, preserved voice, gaps, timed notes, join review, episode approval, downloadable handoff, playback through joins, stable polling, desktop and mobile.');
  console.log('Screenshots: '+output);
  console.log('PASS: character-state upload, human approval, scoped binding preview/discard and project isolation.');
} catch(error){
  if(browser){const pages=browser.contexts()[0]?.pages();if(pages?.[0])await pages[0].screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});}
  console.error(error);process.exitCode=1;
} finally {if(browser)await browser.close();child.kill('SIGTERM');}
