import sys,json,hashlib
from pathlib import Path
sys.path.insert(0,str(Path.cwd()/'engine'))
import cb_gen,cb_render as R
refs=[Path('engine/media/Ep3_S1_SH1_seedream_prompt_trial_v02.png'),Path('cb-seed/assets/final_turnarounds/CB_Keen.jpeg'),Path('cb-seed/assets/final_turnarounds/CB_Zenny.jpeg'),Path('cb-seed/assets/final_turnarounds/CB_Fuzzby.jpeg'),Path('engine/media/Ep3_S1_plate_candidate_c66c0c33.jpeg'),Path('engine/media/asset-registry/Ep3_S1_woodland_catapult.jpeg')]
refs=[str(p.resolve()) for p in refs]
assert all(Path(p).is_file() for p in refs)
prompt='''Edit Image1 into one 16:9 opening keyframe. This is a precise revision of an accepted composition, NOT a new scene. Make only three changes: restore the two bee identities from their authoritative character sheets and enlarge the blueberry for comedy.
Reference responsibilities: Image1 is the base image and sole composition, camera, staging, pose and lighting authority. Image2 is @Keen identity; preserve Keen as in Image1. Image3 is @Zenny identity, with exact facial structure, proportions, silhouette and accessories taken from the entire turnaround. Image4 is @Fuzzby identity with exact facial structure, proportions, silhouette and accessories from the entire turnaround. These two sheets override the imperfect bee identities in Image1; never mix their traits. Image5 is the original Buzzing Nook environment reference for continuity only; do not reframe or rebuild the accepted Image1 environment. Image6 is catapult material/design reference only; do not change Image1's accepted mechanism, orientation or placement. Never copy labels, white backgrounds or multiple views from the reference sheets.
Modification 1: At Image1's existing honeycomb, replace ONLY the bee with faithful @Fuzzby from Image4, asleep with eyes closed, settled body resting physically ON TOP of the honeycomb, paws supported on its upper surface, exact character identity rather than a generic bee. Keep his current screen position and apparent size. Do not put him on a leaf or in flight.
Modification 2: At Image1's existing broad leaf, replace ONLY the bee with faithful @Zenny from Image3, meditating, eyes closed, sitting cross-legged on the leaf with settled weight. Keep current screen position, apparent size and peaceful pose. No facial juice. Do not put her on the honeycomb or in flight.
Modification 3: Enlarge the ONE blueberry in the existing catapult cup until it is comically oversized, approximately the width of Keen's head, bulging well above the cup rim. A clearly recognisable fresh blueberry with natural bloom and crown scar, not a wool ball. Keep its bottom securely cradled inside the cup; enlarge the cup only minimally if necessary to support it. Preserve Keen's hand contacts and the continuous throwing arm.
Preserve everything else in Image1: exactly three characters, Keen's identity and pose, foreground distance to back tree, camera framing, all environment geography, stream, branches, crystals, leaf, catapult position and rearward-loaded launch orientation, and warm lighting. Preserve the vibrant golden honeycomb with wet glistening honey highlights. Do not change honeycomb shape or size. Match existing feature-animation 3D CGI, soft volumetric light, tactile materials and warm harmonious palette. Integrate the revised subjects with coherent contact shadows and perspective.
Exclude: extra characters, generic interchangeable bees, mixed bee identities, extra limbs or accessories, text, arrows, watermark, action montage, flying blueberry, launch, impact, juice, new camera angle or background redesign. Render one clean image only.'''
record={'episode':'Ep3','scene':'1','shot':'S1.SH1','status':'unapproved-comparison','model':cb_gen.SEEDREAM_MODEL_ID,'prompt':prompt,'references':[{'path':p,'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest()} for p in refs]}
meta=Path('cb-output/image-trials/Ep3_S1_SH1_seedream_trial_v03.json');meta.write_text(json.dumps(record,indent=2))
R._require_confirmed_billing('byteplus')
record['output']=cb_gen.generate_image(prompt,refs=refs,out='Ep3_S1_SH1_seedream_prompt_trial_v03.png',image_size='2K',production_route='cb_render')
meta.write_text(json.dumps(record,indent=2));print(record['output'])
